spring:
  application:
    name: dwh-service

server:
  port: 8765

eureka:
  server: 8761
  client:
    service-url:
      defaultZone: http://localhost:${eureka.server}/eureka
  instance:
    prefer-ip-address: true